version: '2.1'
services:
    # First service containing postgres database
    postgres:
        # Build from official image
        image: postgres:9.6
        # Restart if crashed
        restart: always
        # Set environment variables
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        # Attached volumes for persisting data
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
    # Second service containing airflow server
    webserver:
        # Use provided custom Dockerfile to buil
        build:
            context: .
            dockerfile: Dockerfile
        # Restart if crashed
        restart: always
        # Must have postgres container running as dependency
        depends_on:
            - postgres
        # Set environment variables
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        # Attached volumes for persisting data and sharing it with host machine
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./config:/usr/local/airflow/config  
            - ./PDFs:/usr/local/airflow/PDFs
            - ./temp:/usr/local/airflow/temp
            - ./Dataset:/usr/local/airflow/Dataset
            - ./scripts:/usr/local/airflow/scripts
            - ./models:/usr/local/airflow/models
            - ./notebooks:/usr/local/airflow/notebooks
            - ./postgres-data:/var/lib/postgresql/data
        # Map open ports between container and host machine
        ports:
            - "8080:8080"
            - "8888:8888"
        # Entrypoint, run airflow server
        command: webserver
        # Run container health checks periodically
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
